matches:
  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"

  - trigger: ":vg"
    replace: "Vriendelijke groeten,"

  - trigger: ":kr"
    replace: "Kind regards,"

  - trigger: ":br"
    replace: "Best regards,"

  - trigger: ":eu"
    replace: "denis@gontcharov.eu"

  - trigger: ":gm"
    replace: "gontcharovd@gmail.com"

  - trigger: ":str"
    replace: "Begonialaan 9"

  - trigger: ":linkedin"
    replace: "www.linkedin.com/in/gontcharovd"

  - trigger: ":website"
    replace: "https://gontcharov.eu"

  - trigger: ":name"
    replace: "Denis Gontcharov"

  - trigger: ":uns"
    replace: "unified namespace"

  - trigger: ":di"
    replace: "digital infrastructure"

  - trigger: ":ds"
    replace: "digital strategy"

  - trigger: ":dt"
    replace: "digital transformation"

  - trigger: ":cal"
    replace: "https://calendly.com/gontcharovd/introductory-call"

  - trigger: ":ttg"
    replace: "Translate to German: "

  - trigger: ":ftg"
    replace: "Fix this German if necessary: "

  - trigger: ":tel"
    replace: "+49170996377"

  - trigger: ":umh"
    replace: "United Manufacturing Hub"

  - trigger: ":h"
    replace: "--help"

  - trigger: ":os"
    replace: "open-source"

  - trigger: ":adb"
    replace: "Azure Databricks"

  - trigger: ":db"
    replace: "Databricks"

  - trigger: ":yt"
    replace: "YouTube"
